"""Generate seed.sql from JSON reference data.

Reads:
  - reference/stock-universe/{_codes,tdx_industry_56,sectors/index,sectors_concepts_2,sectors_industries_0,sectors_styles_4}.json
  - reference/stock-universe/ths_industry/{industry_list,constituents_crawl_state}.json
  - scheduler/{jobs,turnover_job,auction_analysis_job,market_pulse_job,stock_universe_job,ths_industry_constituents_job}.json

Writes:
  - infra/seed.sql (idempotent: ON CONFLICT everywhere)

v2 changes vs v1:
  - sectors_*: use BIGSERIAL id; natural key = name (UNIQUE)
  - ths_industries: keep code as natural key, but add id BIGSERIAL for FK convenience
  - Removed 'concept:' / 'industry:' / 'style:' prefix hack from IDs
"""
import json
from pathlib import Path
from datetime import datetime

BASE = Path(r'f:\dev-repo\mp4-to-word-new')
REF = BASE / 'reference'
SCH = BASE / 'scheduler'
OUT = BASE / 'infra' / 'seed.sql'


def esc(s):
    """Escape a Python value for a SQL literal.

    - None -> NULL
    - bool -> TRUE / FALSE  (NOT 'True'/'False')
    - int/float -> str
    - everything else -> single-quoted string with embedded ' doubled
    """
    if s is None:
        return 'NULL'
    if isinstance(s, bool):
        return 'TRUE' if s else 'FALSE'
    return "'" + str(s).replace("'", "''") + "'"


def num(v):
    """Render a numeric value or NULL for SQL."""
    if v is None:
        return 'NULL'
    return str(v)


def jsonb_lit(obj):
    """Build a SQL jsonb literal from a Python object."""
    return esc(json.dumps(obj, ensure_ascii=False))


def section(title):
    return f"\n-- ============================================================================\n-- {title}\n-- ============================================================================\n\n"


# --------------------------------------------------------------------------
# Required schema preamble: PG SEQUENCE for any table that needs auto id
# --------------------------------------------------------------------------
SEQUENCES = [
    'sectors_concepts',
    'sectors_industries',
    'sectors_styles',
]


def main():
    parts = []
    parts.append("-- Auto-generated by infra/gen_seed.py on " + datetime.now().isoformat() + "\n")
    parts.append("-- Idempotent seed: every INSERT has ON CONFLICT clause. Safe to re-run.\n")
    parts.append("-- Prereq: infra/scheme.sql already applied (tables exist).\n")
    parts.append("-- IDs are auto-generated via BIGSERIAL. ON CONFLICT keys use natural keys (name / code).\n")
    parts.append("BEGIN;\n\n")

    # ========================================================================
    # §0 PREAMBLE — ensure sequences exist (idempotent CREATE SEQUENCE IF NOT EXISTS)
    # ========================================================================
    parts.append(section("§0 Sequences (auto-generated IDs)"))
    for tbl in SEQUENCES:
        parts.append(
            f"CREATE SEQUENCE IF NOT EXISTS seven_and_me.{tbl}_id_seq OWNED BY seven_and_me.{tbl}.id;\n"
        )
    # Sync the sequence past any existing rows
    for tbl in SEQUENCES:
        parts.append(
            f"SELECT setval('seven_and_me.{tbl}_id_seq', COALESCE((SELECT MAX(id) FROM seven_and_me.{tbl}), 1));\n"
        )
    parts.append("\n")

    # ========================================================================
    # §1 instruments (TDX 56)
    # ========================================================================
    tdx = json.loads((REF / 'stock-universe' / 'tdx_industry_56.json').read_text(encoding='utf-8'))
    parts.append(section(f"§1 instruments (TDX 56, from tdx_industry_56.json)"))
    vals = []
    for code, name in tdx['items'].items():
        full = tdx['prefix'] + code
        vals.append(
            f"    ({esc(f'industry-sh{code}')},'industry','TDX',{esc(code)},{esc(full)},{esc(name)},'tdx_industry_56')"
        )
    parts.append("INSERT INTO seven_and_me.instruments (id, target_type, market, symbol, full_code, name, source) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, full_code=EXCLUDED.full_code, market=EXCLUDED.market, updated_at=now();\n\n")

    # ========================================================================
    # §2 stock_universe_codes + instruments (from _codes.json, 5530)
    # ========================================================================
    codes_doc = json.loads((REF / 'stock-universe' / '_codes.json').read_text(encoding='utf-8'))
    codes = codes_doc.get('codes', [])
    parts.append(section(f"§2 stock_universe_codes + instruments (from _codes.json, {len(codes)} rows)"))

    # §2.1 instruments (full_code PK, batch of 200)
    parts.append(f"-- §2.1 instruments (stock, {len(codes)} rows in batches of 200)\n")
    batch = []
    for c in codes:
        full = c['full_code']
        market = c['exchange'].upper()
        batch.append(
            f"    ({esc(full)},'stock',{esc(market)},{esc(c['code'])},{esc(full)},{esc(c.get('name'))},'eltdx_codes')"
        )
    BATCH = 200
    for i in range(0, len(batch), BATCH):
        chunk = batch[i:i+BATCH]
        parts.append("INSERT INTO seven_and_me.instruments (id, target_type, market, symbol, full_code, name, source) VALUES\n")
        parts.append(",\n".join(chunk))
        parts.append("\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, market=EXCLUDED.market, updated_at=now();\n\n")

    # §2.2 stock_universe_codes
    parts.append(f"-- §2.2 stock_universe_codes ({len(codes)} rows in batches of 200)\n")
    batch = []
    for c in codes:
        full = c['full_code']
        market = c['exchange'].upper()
        batch.append(f"    ({esc(full)},{esc(full)},{esc(market)})")
    for i in range(0, len(batch), BATCH):
        chunk = batch[i:i+BATCH]
        parts.append("INSERT INTO seven_and_me.stock_universe_codes (code, target_id, listed_market) VALUES\n")
        parts.append(",\n".join(chunk))
        parts.append("\nON CONFLICT (code) DO UPDATE SET listed_market=EXCLUDED.listed_market, updated_at=now();\n\n")

    # ========================================================================
    # §3 tdx_industry_56 (56 rows)
    # ========================================================================
    parts.append(section("§3 tdx_industry_56 (56 rows)"))
    vals = []
    for code, name in tdx['items'].items():
        vals.append(f"    ({esc('sh' + code)},{esc(name)})")
    parts.append("INSERT INTO seven_and_me.tdx_industry_56 (industry_code, name) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (industry_code) DO UPDATE SET name=EXCLUDED.name;\n\n")

    # ========================================================================
    # §4 sectors_concepts / sectors_industries / sectors_styles / sectors_index
    # BIGSERIAL id; ON CONFLICT (name) DO UPDATE
    # ========================================================================
    sectors_dir = REF / 'stock-universe' / 'sectors'

    # §4.1 concepts (270)
    sc = json.loads((sectors_dir / 'sectors_concepts_2.json').read_text(encoding='utf-8'))
    parts.append(section(f"§4.1 sectors_concepts (from sectors_concepts_2.json, {len(sc['sectors'])} rows)"))
    vals = []
    for s in sc['sectors']:
        vals.append(f"    ({esc(s['name'])},{esc(sc['fetched_at'])})")
    parts.append("INSERT INTO seven_and_me.sectors_concepts (name, source_updated_at) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (name) DO UPDATE SET source_updated_at=EXCLUDED.source_updated_at, updated_at=now();\n\n")

    # §4.2 industries (2504)
    si = json.loads((sectors_dir / 'sectors_industries_0.json').read_text(encoding='utf-8'))
    parts.append(section(f"§4.2 sectors_industries (from sectors_industries_0.json, {len(si['sectors'])} rows)"))
    vals = []
    for s in si['sectors']:
        vals.append(f"    ({esc(s['name'])},{esc(si['fetched_at'])})")
    parts.append("INSERT INTO seven_and_me.sectors_industries (name, source_updated_at) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (name) DO UPDATE SET source_updated_at=EXCLUDED.source_updated_at, updated_at=now();\n\n")

    # §4.3 styles (140)
    ss = json.loads((sectors_dir / 'sectors_styles_4.json').read_text(encoding='utf-8'))
    parts.append(section(f"§4.3 sectors_styles (from sectors_styles_4.json, {len(ss['sectors'])} rows)"))
    vals = []
    for s in ss['sectors']:
        vals.append(f"    ({esc(s['name'])},{esc(ss['fetched_at'])})")
    parts.append("INSERT INTO seven_and_me.sectors_styles (name, source_updated_at) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (name) DO UPDATE SET source_updated_at=EXCLUDED.source_updated_at, updated_at=now();\n\n")

    # §4.4 sectors_index (singleton)
    idx = json.loads((sectors_dir / 'index.json').read_text(encoding='utf-8'))
    parts.append(section("§4.4 sectors_index (singleton from sectors/index.json)"))
    parts.append("INSERT INTO seven_and_me.sectors_index (id, payload, updated_at) VALUES (\n")
    parts.append(f"    1, {jsonb_lit(idx)}, now()\n")
    parts.append(")\nON CONFLICT (id) DO UPDATE SET payload=EXCLUDED.payload, updated_at=now();\n\n")

    # ========================================================================
    # §5 ths_industries (90, code is natural key)
    # ========================================================================
    ths_il = json.loads((REF / 'stock-universe' / 'ths_industry' / 'industry_list.json').read_text(encoding='utf-8'))
    bycode = ths_il['byCode']
    parts.append(section(f"§5 ths_industries (from industry_list.json, {len(bycode)} rows, code is natural key)"))
    vals = []
    for code, info in bycode.items():
        vals.append(f"    ({esc(code)},{esc(info['name'])})")
    parts.append("INSERT INTO seven_and_me.ths_industries (code, name) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name;\n\n")

    # §5b instruments for THS industries
    parts.append(section("§5b instruments for THS industries (90 rows)"))
    vals = []
    for code, info in bycode.items():
        vals.append(f"    ({esc(f'industry-ths-{code}')},'industry','THS',{esc(code)},{esc(code)},{esc(info['name'])},'ths_industry_list')")
    parts.append("INSERT INTO seven_and_me.instruments (id, target_type, market, symbol, full_code, name, source) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, updated_at=now();\n\n")

    # §5c backfill ths_industries.target_id
    parts.append("-- §5c backfill ths_industries.target_id\n")
    parts.append("UPDATE seven_and_me.ths_industries t SET target_id = 'industry-ths-' || t.code WHERE target_id IS NULL;\n\n")

    # ========================================================================
    # §6 ths_industry_constituents_meta (from constituents_crawl_state.json)
    # ========================================================================
    crawl = json.loads((REF / 'stock-universe' / 'ths_industry' / 'constituents_crawl_state.json').read_text(encoding='utf-8'))
    meta_rows = []
    for run_id, run in crawl['runs'].items():
        run_started = run.get('startedAt')
        industries = run.get('industries', {})
        if not industries and 'targets' in run:
            continue
        for code, info in industries.items():
            fa = info.get('fetchedAt') or run_started
            if not fa:
                continue
            try:
                snap_date = fa.split('T')[0]
            except Exception:
                continue
            meta_rows.append({
                'industry_code': code,
                'snapshot_date': snap_date,
                'ok': info.get('ok', False),
                'total_pages': info.get('pages', 0),
                'row_count': info.get('rows', 0),
                'fetched_at': fa,
            })
    parts.append(section(f"§6 ths_industry_constituents_meta (from constituents_crawl_state.json, dedupe → {len({(m['industry_code'], m['snapshot_date']) for m in meta_rows})} unique)"))
    latest = {}
    for m in meta_rows:
        k = (m['industry_code'], m['snapshot_date'])
        cur = latest.get(k)
        if not cur or m['fetched_at'] > cur['fetched_at']:
            latest[k] = m
    vals = []
    for m in latest.values():
        vals.append(
            f"    ({esc(m['industry_code'])},{esc(m['snapshot_date'])},{esc(m['ok'])},{m['total_pages']},{m['row_count']},{esc(m['fetched_at'])})"
        )
    parts.append("INSERT INTO seven_and_me.ths_industry_constituents_meta (industry_code, snapshot_date, ok, total_pages, row_count, fetched_at) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (industry_code, snapshot_date) DO UPDATE SET ok=EXCLUDED.ok, total_pages=EXCLUDED.total_pages, row_count=GREATEST(seven_and_me.ths_industry_constituents_meta.row_count, EXCLUDED.row_count), fetched_at=EXCLUDED.fetched_at;\n\n")

    # ========================================================================
    # §7 scheduler_jobs (from jobs.json)
    # ========================================================================
    jobs_doc = json.loads((SCH / 'jobs.json').read_text(encoding='utf-8'))
    jobs = jobs_doc['jobs']
    parts.append(section(f"§7 scheduler_jobs (from scheduler/jobs.json, {len(jobs)} rows)"))
    vals = []
    for j in jobs:
        jid = j['id']
        vals.append(
            f"    ({esc(jid)},{esc(j.get('name', jid))},{esc(j.get('description'))},{esc(j.get('config_file'))},{esc(j.get('service_module'))},{esc(j.get('service_class'))},{esc(j.get('enabled', True))},{esc(j.get('registered_at'))})"
        )
    parts.append("INSERT INTO seven_and_me.scheduler_jobs (id, name, description, config_file, service_module, service_class, enabled, registered_at) VALUES\n")
    parts.append(",\n".join(vals))
    parts.append("\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, enabled=EXCLUDED.enabled, updated_at=now();\n\n")

    # ========================================================================
    # §8 scheduler_job_state (from 5 *_job.json)
    # ========================================================================
    state_files = [
        ('turnover_refresh',                  'turnover_job.json'),
        ('auction_ai_analysis',               'auction_analysis_job.json'),
        ('market_pulse',                      'market_pulse_job.json'),
        ('stock_universe_refresh',            'stock_universe_job.json'),
        ('ths_industry_constituents_weekly',  'ths_industry_constituents_job.json'),
    ]
    parts.append(section(f"§8 scheduler_job_state ({len(state_files)} rows, JSONB state holds job-specific fields)"))
    state_vals = []
    for job_id, fname in state_files:
        doc = json.loads((SCH / fname).read_text(encoding='utf-8'))
        saved_at = doc.pop('_saved_at', None)
        schedule = doc.get('schedule')
        schedule_json = json.dumps(schedule, ensure_ascii=False) if schedule else '{}'
        state_only = {k: v for k, v in doc.items() if k not in (
            'enabled', 'schedule', 'timezone_offset_hours', 'tick_seconds',
            'last_run_at', 'last_run_slot', 'last_run_date', 'last_status',
            'last_targets_processed', 'last_duration_seconds', 'last_error',
            'total_runs', 'total_targets_processed', 'total_failures',
        )}
        state_json = json.dumps(state_only, ensure_ascii=False)
        state_vals.append(
            f"    ({esc(job_id)},{esc(doc.get('enabled', True))},{jsonb_lit(schedule_json)},"
            f"{doc.get('timezone_offset_hours', 8)},{doc.get('tick_seconds', 60)},"
            f"{esc(doc.get('last_run_at'))},{esc(doc.get('last_run_slot'))},{esc(doc.get('last_run_date'))},"
            f"{esc(doc.get('last_status'))},{num(doc.get('last_targets_processed'))},"
            f"{num(doc.get('last_duration_seconds'))},{esc(doc.get('last_error'))},"
            f"{num(doc.get('total_runs'))},{num(doc.get('total_targets_processed'))},"
            f"{num(doc.get('total_failures'))},{jsonb_lit(state_json)},{esc(saved_at)})"
        )
    parts.append("INSERT INTO seven_and_me.scheduler_job_state (job_id, enabled, schedule, timezone_offset_hours, tick_seconds,\n    last_run_at, last_run_slot, last_run_date, last_status, last_targets_processed, last_duration_seconds,\n    last_error, total_runs, total_targets_processed, total_failures, state, updated_at) VALUES\n")
    parts.append(",\n".join(state_vals))
    parts.append("\nON CONFLICT (job_id) DO UPDATE SET enabled=EXCLUDED.enabled, schedule=EXCLUDED.schedule,\n    last_run_at=EXCLUDED.last_run_at, last_status=EXCLUDED.last_status,\n    last_targets_processed=EXCLUDED.last_targets_processed, last_duration_seconds=EXCLUDED.last_duration_seconds,\n    total_runs=EXCLUDED.total_runs, total_failures=EXCLUDED.total_failures,\n    state=EXCLUDED.state, updated_at=EXCLUDED.updated_at;\n\n")

    # ========================================================================
    # §9 ths_industry_constituents.rows (NOT generated here; see note)
    # ========================================================================
    parts.append(section("§9 ths_industry_constituents.rows (NOT generated here; see note)"))

    parts.append("COMMIT;\n\n")
    parts.append("-- ============================================================================\n-- Verification (uncomment to run)\n-- ============================================================================\n")
    parts.append("""-- SELECT 'instruments' AS tbl, COUNT(*) AS n FROM seven_and_me.instruments
-- UNION ALL SELECT 'stock_universe_codes', COUNT(*) FROM seven_and_me.stock_universe_codes
-- UNION ALL SELECT 'tdx_industry_56', COUNT(*) FROM seven_and_me.tdx_industry_56
-- UNION ALL SELECT 'sectors_concepts', COUNT(*) FROM seven_and_me.sectors_concepts
-- UNION ALL SELECT 'sectors_industries', COUNT(*) FROM seven_and_me.sectors_industries
-- UNION ALL SELECT 'sectors_styles', COUNT(*) FROM seven_and_me.sectors_styles
-- UNION ALL SELECT 'sectors_index', COUNT(*) FROM seven_and_me.sectors_index
-- UNION ALL SELECT 'ths_industries', COUNT(*) FROM seven_and_me.ths_industries
-- UNION ALL SELECT 'ths_industry_constituents_meta', COUNT(*) FROM seven_and_me.ths_industry_constituents_meta
-- UNION ALL SELECT 'scheduler_jobs', COUNT(*) FROM seven_and_me.scheduler_jobs
-- UNION ALL SELECT 'scheduler_job_state', COUNT(*) FROM seven_and_me.scheduler_job_state;
""")

    OUT.write_text(''.join(parts), encoding='utf-8')
    size_kb = OUT.stat().st_size / 1024
    print(f"[OK] wrote {OUT} ({size_kb:.1f} KB)")
    counts = {
        'instruments (TDX)': len(tdx['items']),
        'instruments (THS industries)': len(bycode),
        'stock_universe_codes': len(codes),
        'sectors_concepts': len(sc['sectors']),
        'sectors_industries': len(si['sectors']),
        'sectors_styles': len(ss['sectors']),
        'ths_industries': len(bycode),
        'ths_industry_constituents_meta (unique)': len(latest),
        'scheduler_jobs': len(jobs),
        'scheduler_job_state': len(state_files),
    }
    for k, v in counts.items():
        print(f"  - {k}: {v}")


if __name__ == '__main__':
    main()